name: benchmarks

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  benchmarks:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0-beta.3"
      - name: Install local version of pytest-codspeed
        run: pip install .
      - name: Run benchmarks
        uses: CodSpeedHQ/action@main
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests/benchmarks/ --codspeed
